
str_var = str("Hello World")		
int_var = int(20)	
float_var = float(20.5)	
complex_var = complex(1j)	
list_var = list(("apple", "banana", "cherry"))		
tuple_var = tuple(("apple", "banana", "cherry"))	
range_var = range(6)	
dict_var = dict(name="John", age=36)	
set_var = set(("apple", "banana", "cherry"))	
frozenset_var = frozenset(("apple", "banana", "cherry"))		
bool_var = bool(5)	
bytes_var = bytes(5)
bytearray_var = bytearray(5)
memoryview_var = memoryview(bytes(500000000))
