
a = str("Hello World")		
b = int(20)	
c = float(20.5)	
d = complex(1j)	
e = list(("apple", "banana", "cherry"))		
f = tuple(("apple", "banana", "cherry"))	
g = range(6)	
h = dict(name="John", age=36)	
i = set(("apple", "banana", "cherry"))	
j = frozenset(("apple", "banana", "cherry"))		
k = bool(5)	
l = bytes(5)
m = bytearray(5)
n = memoryview(bytes(500000000))
